### ISSUE TITLE
How do you access fields in the returned `Row` generated function?

### ISSUE THREAD

**Issue by Trii** [mafintosh/csv-parser#127] opened 2019-03-11 20:15 UTC
Documentation Is:

```javascript
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: '24' },
    //   { NAME: 'Bugs Bunny', AGE: '22' }
    // ]
  });
```

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
Using the example above, how would you access the `NAME` column of `results[0]`? I've tried `results[0].NAME` and `results[0]['NAME']` and both are undefined.

### Your Proposal for Changes
Add a use case for `console.log`'ing a property column value

This is what I have tried
```javascript
> typeof results[0]
'object'
> Object.getOwnPropertyNames(results[0])
[ 'NAME' ]
> results[0]
Row { 'NAME': 'Daffy Duck' }
> results[0].NAME
undefined
> results[0]['NAME']
undefined
```

**Comment by shellscape** [comment] 2019-03-11 22:06
_(Cheers fellow Floridian)_

I'm not sure what the difference between our two environments is (Node 10.15.0 here), but the example works perfectly for me. Just to sanity test this I used `test/data/dummy.csv` and updated the data to reflect that used in the README. Here's the code I used in a file named `s.js` in the repo:

```js
const csv = require('./')
const fs = require('fs')
const results = []

fs.createReadStream('test/data/dummy.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results[0])
  })
```

And here's running it in the console:

```console
computer: ~/code/csv-parser 
→ node s
Row { NAME: 'Daffy Duck', AGE: '24' }
```

All looked well. I changed the log line to `console.log(results[0].NAME)`.

```console                                                                                                                         
computer: ~/code/csv-parser
→ node s
Daffy Duck
```

Looks like the result we were after. From my end there doesn't look to be a problem.

**Comment by shellscape** [comment] 2019-03-12 01:11
So I tested on Node 8, 10, and 11. Try as I might, I can't reproduce the situation in which `results[0].NAME` is `undefined`.  Because of that, I'm going to mark that as could not reproduce and close it. If you come up with a reproducible scenario, please create a repository with information on how the environment should be set up, and post that here and we'll reopen and investigate using your repo.

**Closed by shellscape** 2019-03-12 01:11 UTC
Labels: x² ⋅ could not reproduce

**Comment by Trii** [comment] 2019-03-12 01:15
Hrm. I'll check again tomorrow. The one difference is that my input csv is only a single column with no comma. Thanks!

**Comment by Trii** [comment] 2019-03-12 15:34
Looks like it was an input file error. When I create a file by hand with:

```
NAME
josh
```
Then it works as expected. When I export data from a jira script, it always prints `undefined` for the first column. If I have more than one column, columns 2-N all work as expected.

**Comment by xzeno** [comment] 2019-05-10 17:19
```javascript
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('keywords.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
  	var rows = JSON.parse(JSON.stringify(results))
  	console.log(rows[0].NAME);
  });
```

**Comment by mdjaman** [comment] 2019-07-16 11:20
Have the same issue environment node v9.5.0

**Comment by shellscape** [comment] 2019-07-16 12:18
@mdjaman please don't reply with "+1," "me too," or "same issue" replies. Instead, use the reaction buttons to show support for an issue or other reply.

**Comment by nccho** [comment] 2024-09-04 00:14
https://github.com/mafintosh/csv-parser?tab=readme-ov-file#byte-order-marks

Byte Order Mark 로 인해 문제가 발생할 수 있습니다.
strip-bom-stream 모듈을 사용해서 해결하는 방법이 제시 되어 있지만
commonjs 방식을 이용하는 저의 경우 strip-bom-stream 모듈은 require() 할 수가 없었습니다.

ChatGPT 도움으로 아래와 같이 BOM을 체크하고 제거하는 클래스를 만들어서 해결 했습니다

----
Byte Order Mark could cause problems.
The strip-bom-stream module was suggested as a workaround.
In my case, using the commonjs method, I couldn't require() the strip-bom-stream module.

With the help of ChatGPT, I solved it by creating a class to check and remove the BOM as shown below.

```
const { Transform } = require('stream')

// Remove BOM using Transform stream
class RemoveBOM extends Transform {
  constructor(options) {
    super(options)
    this.firstChunk = true
  }

  _transform(chunk, encoding, callback) {
    if (this.firstChunk) {
      this.firstChunk = false
      // Check BOM
      if (chunk[0] === 0xEF && chunk[1] === 0xBB && chunk[2] === 0xBF) {
        // Remove BOM and push the rest
        chunk = chunk.slice(3)
      }
    }
    this.push(chunk)
    callback()
  }
}

module.exports = RemoveBOM

// example
 fs.createReadStream('inputFilePath')
   .pipe(new RemoveBOM())
   .pipe(fs.createWriteStream('outputFilePath'))
   .on('finish', () => {
     console.log('BOM Complete!')
})
```
