### ISSUE TITLE
how to read each row and insert into database along with remove unwant white space as well as multiple comma

### ISSUE THREAD

**Issue by bipinshukla** [mafintosh/csv-parser#114] opened 2019-01-03 13:51 UTC
hello guys, i go through document but have n't find any solution moreover i read all read me but haven't find any solution related to this situatuion
        [ Row {
            bankcustomers_id: '154491',
            customerid: '154491',
            title: 'MR ',
            firstname: 'Santa          ',
            lastname: 'Clause                             ',
            dob: '25-Dec-30',
            mobileno: '07900 1234567  ',
            emailid: 'santa-clause@northpole                       ',
            housenumber: '5',
            address1: '5 North Street                          ',
            address2: 'Pole                                    ',
            address3: 'London                                  ',
            address4: '                                        ',
            address5: '                                        ',
            postcode: 'DY3 11X     
                                                                                                                            ' }]
above is output is product by csv parser now my problem is that is there any provision to remove this white space at start and last of  charater or  consecutive ,, .and how i can get single column value .how i can remove all mention this is there anybody help me out with this 

moreover  i want to insert each row into data base so how i can read row on this function 
         .on('data', (data) =>{
            //    console.log(data)
              results.push(data)
            })

**Comment by shellscape** [comment] 2019-01-03 13:56
Duplicate of https://github.com/mafintosh/csv-parser/issues/113

**Closed** 2019-01-03 13:55 UTC
