### ISSUE TITLE
No error event?

### ISSUE THREAD

**Issue by rightaway** [mafintosh/csv-parser#62] opened 2016-10-30 21:50 UTC
I get a `Error: Row length does not match headers` if a row's length doesn't match its headers, which causes parsing of the whole file to fail. Is there not a way to log the invalid row with something like an `error` or `invalid` event, allowing the rest of the file's parsing to continue?

**Comment by tsvetann** [comment] 2016-12-15 17:03
that surprised me as well

**Comment by TheBrianJ** [comment] 2016-12-16 23:44
@rightaway are you setting `strict:true` in the options?

**Comment by tsvetann** [comment] 2016-12-17 12:48
This is how I setup mine:

```
var stream = csv({
    raw: false,     // do not decode to utf-8 strings
    separator: '|', // specify optional cell separator
    quote: '"',     // specify optional quote character
    escape: '\\',    // specify optional escape character (defaults to quote value)
    newline: '\n',  // specify a newline character
    strict: true
})
```

It will be very useful if we can get more error reporting about which column does not match...etc.

Thanks @TheBrianJ

**Comment by TheBrianJ** [comment] 2016-12-17 14:59
@tsvetann right the `strict:true` is what's causing the errors.  I don't think you can say "which column doesn't match" since all it does is check the length: https://github.com/mafintosh/csv-parser/blob/master/index.js#L158-L163

```
  if (this.strict && cells.length !== this.headers.length) {
    this.emit('error', new Error('Row length does not match headers'))
  } else {
    this._emit(this._Row, cells)
  }
```

Suppose you had a file like

```
Name,Date,Notes
foo,20161016,bar
baz,qux
```

based on the column labels, you would reasonably guess that the date is missing from the second row.  But for the parser to make that guess, it would require serious heuristics that are probably beyond the scope of a simple CSV parser.

**Comment by tsvetann** [comment] 2016-12-17 17:17
@TheBrianJ right. what you are saying makes sense. However, I experienced this error on a row that has exactly as many columns as the header. When I logged `cells.length` and `this.headers.length` I noticed that `cells.length` was unrealistically high number such as 4k+ which makes me think that somehow the parser parses the rest of the file as one line. But I have no clue on how to debug further as it gives me no meaningful error!

**Comment by TheBrianJ** [comment] 2016-12-17 17:22
@tsvetann do you have an example file? it sounds like you might have run into a different sort of bug

**Comment by tsvetann** [comment] 2016-12-17 17:28
@TheBrianJ it's definitely not csv-parser bug! Maybe some hidden chars...I don't know. What I was trying to say is that csv-parser is not very helpful to debug, hence reaching out for advice. Unfortunately, I cannot provide any of the files as they contain sensitive customer data. All I can say after inspection I found nothing obviously wrong with the files. All I was able to find out is the erroneous line and after removing it all worked like charm.

**Comment by TheBrianJ** [comment] 2016-12-17 17:46
@tsvetann it may be a bug for all we know! Can you take the file and just replace all of the letters with "J" and all of the digits with "0"?  That way the sensitive information is removed (unless you used a base-1 encoding of the data 😆 )

**Comment by shellscape** [comment] 2018-08-18 16:37
Closing citing age of the issue and last comment date. If this persists as a bug for anyone else, please open a new issue and provide a link to some sample data that we can use to reproduce.

**Closed by shellscape** 2018-08-18 16:37 UTC
